### ISSUE TITLE
question about tests

### ISSUE THREAD

**Issue by ZTzxj** [google/diffseg#2]
Hello, I'd like to ask if you have the complete code for running performance tests.

**Comment by margonzalezfranco** [comment]
Hi! We have added the test and evaluation code for our two benchmarks! Enjoy :)

**Comment by ZTzxj** [comment]
Thanks! ！





甄婷
***@***.***

签名由 网易灵犀办公 定制





Original:
From: Mar ***@***.***> Date: 2023-12-30 02:28:06 To: ***@***.***> Cc: ***@***.***>, ***@***.***> Subject: Re: [google/diffseg] question about tests (Issue #2)
Hi! We have added the test and evaluation code for our two benchmarks! Enjoy :)
